### ISSUE TITLE
[Docs] Default config values

### ISSUE THREAD

**Issue by th3fallen** [BetterTyped/hyper-fetch#18]
for the overwhelming majority of config object definitions you have a column for default value but they're always `-`
it would be extremely helpful to have the defaults documented.

for example, https://hyperfetch.bettertyped.com/api/Hyper-Fetch/Class/Command
or https://hyperfetch.bettertyped.com/api/Hyper-Fetch/Type%20alias/CommandConfig

**Comment by prc5** [comment]
We have now started to make the first major changes to the api generator, hence the values and the overall look of the documentation will change and improve from release to release, adding new features and correcting existing issues. It looks a lot better now and hopefully both the api and the main documentation have improved a lot after the recent fixes! There will be even more changes coming soon, and I hope this will meet the expectations of as many people as possible. Let me close this issue because we implement new forms of presentation of our api, abandoning the old generation method due to its experimental functionality. Thanks for the feedback! 🤝
