### ISSUE TITLE
Support Angular, Svelte, Vue and others.

### ISSUE THREAD

**Issue by atilkan** [BetterTyped/hyper-fetch#29]
**Is your feature request related to a problem? Please describe.**
This is on the homepage.
`For any Javascript / Typescript environment like Node.js, React, Angular, Svelte, Vue and others.`

**Additional context**
There is a React adapter but no other information about other frameworks. Is this really framework agnostic? Do we need adapters?

**Comment by prc5** [comment]
Hey @atilkan! This are good questions, but the answer is a bit more multi-level.

**1. Is this really framework agnostic?**
Yes. Core logic is just pure js, it is not related to any framework or library. So you can do the following in any evnironment:

```tsx
const [data, error, status] = await command.send()
```

The core logic handles everything, cache, dispatching, queueing, client, offline, deduplication, cancelation etc. This means you got everything needed to make it work with core package, no matter of the framework. Of course we will try to provide as many adapters to make it easier for anyone to use our package.

**2. Do we need adapters?**

Sort answer is yes and no. 

**Yes** - because it's always better to use something created for your environment, which respects and understand lifecycle  and the correct style in which Hyper Fetch should behave. As for **React** what the adapter hooks do is just connecting to proper event emitters, handles lifecycle, limitting unnecessary rerendering and refreshing our data. That's really all, hooks are quite short for react, just because main package do the most of the work.

**No** - because you can still use core package in any environment or create your own set of adapters to make it work better for your environment, with all the events we are emitting it should be much easier to manage. As I mentioned, core package is doing a lot of stuff.

**Summary**
Of course, that doesn't mean the library will stay that way, I'm currently working on implementing websockets and adding the final important modules to the system to make it truly "complete". Thanks to this, we will be able to focus on many adapters and integrations. We have a lot planned, and thanks to the tools we have already created, the whole process will most likely run very quickly and efficiently.

Let me know if you have any additional questions 👍🏻

**Comment by atilkan** [comment]
Please dont forget that there are other frameworks. Thank you.
